dist: trusty
sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libglib2.0-dev

matrix:
  allow_failures:
    - rust: nightly

script:
    - rustc --version
    - cargo build --all
    - cargo test --all
