// This file was generated by gir (https://github.com/gtk-rs/gir @ bfd4346+)
// from gir-files (https://github.com/gtk-rs/gir-files @ 2b56823)
// DO NOT EDIT


#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]
pub mod application;
