// This file was generated by gir (https://github.com/gtk-rs/gir @ a3d21e2+)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8+)
// DO NOT EDIT

extern crate glib_sys as glib_ffi;
extern crate gio_sys as gio_ffi;
#[macro_use]
extern crate glib;
extern crate gio;


pub mod action;

pub mod action_group;

pub mod action_map;

pub mod app_info;

pub mod app_launch_context;

pub mod application;

pub mod drive;

pub mod menu;

pub mod menu_attribute_iter;

pub mod menu_item;

pub mod menu_link_iter;

pub mod menu_model;

pub mod mount;

pub mod permission;

pub mod settings;

pub mod simple_action;

pub mod simple_action_group;

pub mod simple_permission;

pub mod volume;

pub mod volume_monitor;
