// This file was generated by gir (https://github.com/gtk-rs/gir @ a3d21e2+)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8+)
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]

extern crate libc;

#[allow(unused_imports)]
use libc::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
    c_short, c_ushort, c_long, c_ulong,
    c_void, size_t, ssize_t, intptr_t, uintptr_t, time_t, FILE};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};

use ffi;
use glib;
use glib::object::IsA;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;


pub trait MenuAttributeIterImpl<T: MenuAttributeIterBase>: ObjectImpl<T> + AnyImpl + 'static {

    fn get_next(&self, iter: &T) -> Option<(String, glib::Variant)>{
        iter.parent_get_next()
    }

}

pub trait MenuAttributeIterImplExt<T> {}

}
impl<S: MenuAttributeIterImpl<T>, T: ObjectType >> MenuAttributeIterImplExt<T> for S {}

any_impl!(MenuAttributeIterBase, MenuAttributeIterImpl);

pub unsafe trait MenuAttributeIterBase: ObjectType {

    fn parent_get_next(&self) -> Option<(String, glib::Variant)>{
        unsafe {
            let klass = self.get_class();
            let parent_klass = (*klass).get_parent_class() as *const ffi::GMenuAttributeIterClass;
            (*parent_klass)
            .get_next
            .map(|f|{ let mut out_name = ptr::null(); let mut value = ptr::null_mut(); let ret = from_glib(f(self.to_glib_none().0,out_name.to_glib_none_mut().0,value.to_glib_full())); if ret { Some((from_glib_none(out_name), from_glib_full(value))) } else { None } })
            .unwrap_or(())
        }
    }

}

pub unsafe trait MenuAttributeIterClassExt<T: MenuAttributeIterBase>
where
    T::ImplType: MenuAttributeIterImpl<T>{

    fn override_vfuncs(&mut self, _: &ClassInitToken){
        unsafe {
            let klass = &mut *(self as *const Self as *mut ffi::GMenuAttributeIterClass);
            klass.get_next = Some(menuattributeiter_get_next::<T>);
        }
    }

}

glib_wrapper! {

    pub struct MenuAttributeIter(Object<InstanceStruct<MenuAttributeIter>>)    ;
    match fn { 
         get_type => || get_type::<MenuAttributeIter>(),
     }

}

unsafe impl<T: ObjectType > MenuAttributeIterBase for T {}

pub type MenuAttributeIterClass = ClassStruct<MenuAttributeIter>;

// FIXME: Boilerplate

// FIXME: Boilerplate

#[macro_export]
macro_rules! box_menuattributeiter_impl(
    ($name:ident) => {
        box_object_impl!($name);
        impl<T: $crate::menu_attribute_iter::MenuAttributeIterBase> $crate::menu_attribute_iter::MenuAttributeIterImpl<T> for Box<$name<T>>{

            fn get_next(&self, iter: &T) -> Option<(String, glib::Variant)>{
                let imp: &$name<T> = self.as_ref();
                imp.get_next()
            }
        }
    }
);

impl ObjectType for MenuAttributeIter{
    const NAME: &'static str = "RsGio.MenuAttributeIter";
    type ImplType = Box<MenuAttributeIterImpl<Self>>;
    type InstanceStructType = InstanceStruct<Self>;
    fn class_init(token: &ClassInitToken, klass: &mut MenuAttributeIterClass) {
        ObjectClassExt::override_vfuncs(klass, token);
    }
    object_type_fns!();
}

unsafe extern "C" fn menuattributeiter_get_next<T: MenuAttributeIterBase>
(ptr: *mut GMenuAttributeIter, out_name: *mut *const c_char, value: *mut *mut glib::GVariant) -> gboolean
where
    T::ImplType: MenuAttributeIterImpl<T>
{
    callback_guard!();
    floating_reference_guard!(ptr);
    let menuattributeiter = &*(ptr as *mut T::InstanceStructType);
    let wrap: T = from_glib_borrow(ptr as *mut T::InstanceStructType);
    let imp = menuattributeiter.get_impl();
    imp.get_next()
}
