// This file was generated by gir (https://github.com/gtk-rs/gir @ a3d21e2+)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8+)
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]

extern crate libc;

#[allow(unused_imports)]
use libc::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
    c_short, c_ushort, c_long, c_ulong,
    c_void, size_t, ssize_t, intptr_t, uintptr_t, time_t, FILE};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};

use Permission;
use ffi;
use glib::object::Downcast;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::mem;
use std::ptr;


pub trait SimplePermissionImpl<T: SimplePermissionBase>: gio_subclass::PermissionImpl<T> + ObjectImpl<T> + AnyImpl + 'static {

}

pub trait SimplePermissionImplExt<T> {}

}
impl<S: SimplePermissionImpl<T>, T: ObjectType + glib::IsA<gio::Permission>>> SimplePermissionImplExt<T> for S {}

any_impl!(SimplePermissionBase, SimplePermissionImpl);

pub unsafe trait SimplePermissionBase: ObjectType + glib::IsA<gio::Permission>{

}

glib_wrapper! {

    pub struct SimplePermission(Object<InstanceStruct<SimplePermission>>):[
         gio::Permission => gio_ffi::GPermission]    ;
    match fn { 
         get_type => || get_type::<SimplePermission>(),
     }

}

unsafe impl<T: ObjectType + glib::IsA<gio::Permission>> SimplePermissionBase for T {}

pub type SimplePermissionClass = ClassStruct<SimplePermission>;

// FIXME: Boilerplate
unsafe impl PermissionClassExt<SimplePermission> for SimplePermissionClass {}

// FIXME: Boilerplate
unsafe impl PermissionClassExt<SimplePermission> for SimplePermissionClass {}

#[macro_export]
macro_rules! box_simplepermission_impl(
    ($name:ident) => {
        box_permission_impl!($name);
        impl<T: $crate::simple_permission::SimplePermissionBase> $crate::simple_permission::SimplePermissionImpl<T> for Box<$name<T>>{
        }
    }
);

impl ObjectType for SimplePermission{
    const NAME: &'static str = "RsGio.SimplePermission";
    type ParentType = gio::Permission;
    type ImplType = Box<SimplePermissionImpl<Self>>;
    type InstanceStructType = InstanceStruct<Self>;
    fn class_init(token: &ClassInitToken, klass: &mut SimplePermissionClass) {
        ObjectClassExt::override_vfuncs(klass, token);
        PermissionClassExt::override_vfuncs(klass, token);
    }
    object_type_fns!();
}
