// This file was generated by gir (https://github.com/gtk-rs/gir @ a3d21e2+)
// from gir-files (https://github.com/gtk-rs/gir-files @ b215ee8+)
// DO NOT EDIT

#![allow(non_camel_case_types, non_upper_case_globals, non_snake_case)]

extern crate libc;

#[allow(unused_imports)]
use libc::{c_int, c_char, c_uchar, c_float, c_uint, c_double,
    c_short, c_ushort, c_long, c_ulong,
    c_void, size_t, ssize_t, intptr_t, uintptr_t, time_t, FILE};

#[allow(unused_imports)]
use glib::{gboolean, gconstpointer, gpointer, GType};

use Action;
use ffi;
use glib;
use glib::Value;
use glib::object::Downcast;
use glib::object::IsA;
use glib::signal::SignalHandlerId;
use glib::signal::connect;
use glib::translate::*;
use glib_ffi;
use gobject_ffi;
use std::boxed::Box as Box_;
use std::mem;
use std::mem::transmute;
use std::ptr;


pub trait SimpleActionImpl<T: SimpleActionBase>: gio_subclass::ActionImpl<T> + ObjectImpl<T> + AnyImpl + 'static {

}

pub trait SimpleActionImplExt<T> {}

}
impl<S: SimpleActionImpl<T>, T: ObjectType + glib::IsA<gio::Action>>> SimpleActionImplExt<T> for S {}

any_impl!(SimpleActionBase, SimpleActionImpl);

pub unsafe trait SimpleActionBase: ObjectType + glib::IsA<gio::Action>{

}

glib_wrapper! {

    pub struct SimpleAction(Object<InstanceStruct<SimpleAction>>):[
         gio::Action => gio_ffi::GAction]    ;
    match fn { 
         get_type => || get_type::<SimpleAction>(),
     }

}

unsafe impl<T: ObjectType + glib::IsA<gio::Action>> SimpleActionBase for T {}

pub type SimpleActionClass = ClassStruct<SimpleAction>;

// FIXME: Boilerplate
unsafe impl ActionClassExt<SimpleAction> for SimpleActionClass {}

// FIXME: Boilerplate
unsafe impl ActionClassExt<SimpleAction> for SimpleActionClass {}

#[macro_export]
macro_rules! box_simpleaction_impl(
    ($name:ident) => {
        box_action_impl!($name);
        impl<T: $crate::simple_action::SimpleActionBase> $crate::simple_action::SimpleActionImpl<T> for Box<$name<T>>{
        }
    }
);

impl ObjectType for SimpleAction{
    const NAME: &'static str = "RsGio.SimpleAction";
    type ImplType = Box<SimpleActionImpl<Self>>;
    type InstanceStructType = InstanceStruct<Self>;
    fn class_init(token: &ClassInitToken, klass: &mut SimpleActionClass) {
        ObjectClassExt::override_vfuncs(klass, token);
        ActionClassExt::override_vfuncs(klass, token);
    }
    object_type_fns!();
}
